---
dependency:
  name: galaxy
  enabled: true
  options:
    role-file: molecule/shared/requirements.yml
    requirements-file: molecule/shared/collections.yml
driver:
  name: docker
lint: |
  ansible-lint
platforms:
  - name: ubuntu2004
    image: bwinfosec/ubuntu2004-systemd
    privileged: true
    override_command: false
    dns_servers:
      - 1.1.1.1
      - 8.8.8.8
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    prepare: ../shared/prepare.yml
    verify: ../shared/verify.yml
verifier:
  name: ansible
