name: Molecule Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - debian
          - ubuntu
    steps:
      - name: Disable git stricter reository ownership
        run: echo "[safe]\n directory = *" | sudo tee /etc/gitconfig 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
